export const LOGIN_USER = "LOGIN_USER";

export const GET_CATALOG_LIST = "GET_CATALOG_LIST";
export const CREATE_CATALOG = "CREATE_CATALOG";
export const RETRIEVE_CATALOG = "RETRIEVE_CATALOG";
export const UPDATE_CATALOG = "UPDATE_CATALOG";
export const DELETE_CATALOG = "DELETE_CATALOG";
export const DELETE_ALL_CATALOGS = "DELETE_ALL_CATALOGS";
